// GLOBALS

const STAFF_TOP_MARGIN = 100.0;
const STAFF_LEFT_MARGIN = 50.0;
const STAFF_WIDTH = 900.0;

const STAFF_LINE_THICKNESS = 3.0;
const STAFF_DISTANCE = 20.0;

const STAFF_LINE_COUNT = 5;
const STAFF_COUNT_IN_PAGE = 5;

// Computed globals
const STAFF_END = STAFF_WIDTH + STAFF_DISTANCE;
const STAFF_HEIGHT = 1 * STAFF_DISTANCE;
const SCORE_OVAL_HEIGHT = STAFF_DISTANCE;
const SCORE_OVAL_WIDTH = STAFF_DISTANCE * 2;
